#! /bin/sh

### BEGIN INIT INFO
# Provides:          pg_datalinker
# Required-Start:    $local_fs $remote_fs $networkOB
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start PostgreSQL datalinker
# Description:       This script provides a PostgreSQL SQL/MED like datalinker
### END INIT INFO

# Source function library
. /lib/lsb/init-functions

NAME=pg_datalinker
DESC="SQL/MED datalinker"
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/postgresql_datalinker
PIDFILE=/run/$NAME.pid

test -x $DAEMON || exit 0

# Include varnish defaults if available
if [ -f /etc/default/${NAME} ] ; then
        . /etc/default/${NAME}
fi

# If $DAEMON_OPTS is not set at all in /etc/default/, use minimal useful
# defaults 
DAEMON_OPTS=${DAEMON_OPTS:}

# Ensure we have a PATH
export PATH="${PATH:+$PATH:}/usr/sbin:/usr/bin:/sbin:/bin"

start_datalinker() {
    log_daemon_msg "Starting $DESC" "$NAME"
    output=/var/log/postgresql/${NAME}.log
    if start-stop-daemon \
        --start --quiet --pidfile ${PIDFILE} --exec ${DAEMON} -- \
        -P ${PIDFILE} ${DAEMON_OPTS} > ${output} 2>&1; then
        log_end_msg 0
    else
        log_end_msg 1
        cat $output
        exit 1
    fi
    rm $output
}

disabled_datalinker() {
    log_daemon_msg "Not starting $DESC" "$NAME"
    log_progress_msg "disabled in /etc/default/$NAME"
    log_end_msg 0
}

stop_datalinker() {
    log_daemon_msg "Stopping $DESC" "$NAME"
    if start-stop-daemon \
        --stop --quiet --pidfile $PIDFILE --retry 10 \
        --exec $DAEMON; then
        log_end_msg 0
    else
        log_end_msg 1
    fi

    if test -r $PIDFILE; then
        read -r PID < $PIDFILE
        if test ! -d /proc/$PID ; then
            # stale pidfile
            unset PID
            rm -f $PIDFILE
        fi
    fi
}

reload_datalinker() {
    log_daemon_msg "Reloading $DESC" "$NAME"
    if start-stop-daemon \
        --stop --signal 1 --quiet --pidfile $PIDFILE  \
        --exec $DAEMON; then
        log_end_msg 0
    else
        log_end_msg 1
    fi
}

status_datalinker() {
    start-stop-daemon \
        --status --quiet --pidfile $PIDFILE \
        --exec $DAEMON
    exit $?
}

configtest() {
    $DAEMON ${DAEMON_OPTS} -C > /dev/null
}



case "$1" in
    start)
        case "${START:-}" in
            [Yy]es|[Yy]|1|[Tt]|[Tt]rue)
                start_datalinker
                ;;
            *)
                disabled_datalinker
                ;;
        esac
        ;;
    stop)
        stop_datalinker
        ;;
    reload)
        reload_datalinker
        ;;
    status)
        status_datalinker
        ;;
    restart|force-reload)
	if status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}" 1>/dev/null; then
	    if ! configtest; then
		log_failure_msg "Syntax check failed, not restarting"
		exit 1
	    fi
	fi
        $0 stop
        $0 start
        ;;
    configtest)
        configtest && log_success_msg "Syntax ok"
        ;;
    *)
        log_success_msg "Usage: $0 {start|stop|restart|reload|force-reload|configtest}"
        exit 1
        ;;
esac
